---

- name: Update config kubelet
  template: 
    src: kubelet_config.yaml.j2 
    dest: "/var/lib/kubelet/config.yaml"

- name: Daemon-reload
  command: systemctl daemon-reload

- name: Restart Kubelet
  command: systemctl restart kubelet

- name: Create cluster
  command: kubeadm init --pod-network-cidr=192.168.0.0/16 --ignore-preflight-errors=all

- name: Give kubectl rights to another user than root - 1
  shell: mkdir -p $HOME/.kube

- name: Give kubectl rights to another user than root - 2
  shell: sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config

- name: Give kubectl rights to another user than root - 3
  shell: sudo chown $(id -u):$(id -g) $HOME/.kube/config
  
- name: Config for root user
  shell: export KUBECONFIG=/etc/kubernetes/admin.conf
